// Straipsnių duomenys
const straipsniuDuomenys = [
  {
    "id": 1,
    "pavadinimas": "Traumos tyrimai Baltijos šalyse: nuo politinio engimo iki atsigavimo",
    "autoriai": "Evaldas Kazlauskas ir Paulina Zelvienė",
    "institucija": "Klinikines ir organizacinės psichologijos katedra, Vilniaus universitetas, Vilnius, Lietuva",
    "metai": 2016,
    "santrauka": "Šio straipsnio tikslas – pateikti trauminio streso tyrimų apžvalgą iš trijų Baltijos šalių – Lietuvos, Latvijos ir Estijos – ir atskleisti, kaip specifinis socialinis kontekstas prisideda prie aktualių temų trauminio streso srityje regione. Trauminio streso tyrimai Baltijos šalyse yra glaudžiai susiję su sudėtinga regiono istorija. Tik po Baltijos valstybių nepriklausomybės atkūrimo 1990-aisiais galėjo atsirasti trauminio streso tyrimai. Psihotraumatologijos pradžią Baltijos šalyse įkvėpė susidomėjimas politinio smurto psichologiniais poveikiais. Šiame straipsnyje buvo nustatytos keturios pagrindinės temos trauminio streso literatūroje iš Baltijos šalių: politinio smurto tyrimai, traumos ir potrauminio streso sutrikimo (PTSS) epidemiologija, nelaimių tyrimai ir traumos raidos aspektai. Baltijos šalyse trauminių įvykių paplitimas buvo nustatytas tarp 70 ir 75%, o PTSS paplitimas – 2-7%. Susidomėjimas psihotraumatologija Baltijos šalyse didėja.",
    "raktiniai_zodziai": ["Potrauminis stresas", "apžvalga", "trauma", "Baltija", "Lietuva", "Latvija", "Estija"],
    "turinys": {
      "ivadinė_dalis": "Lietuva, Latvija ir Estija – trys Baltijos šalys (taip pat žinomos kaip Baltijos valstybės ar Baltija) – yra išsidėsčiusios priešingame Baltijos jūros krante nuo Švedijos ir Suomijos, šiaurės rytiniame Europos Sąjungos (ES) pakraštyje, tarp Rusijos ir kitų ES šalių. Esant maždaug 6 milijonų gyventojų, regionas patyrė reikšmingų socialinių pokyčių per pastaruosius kelis dešimtmečius. Bendra Baltijos šalių istorija prasidėjo 1918 m. po Pirmojo pasaulinio karo, kai Europos žemėlapyje atsirado naujos šalys, įskaitant Lietuvą, Latviją ir Estiją. Nepriklausomų Baltijos šalių vystymąsi sugriovė su Antruoju pasauliniu karu (Antrasis pasaulinis karas) susiję įvykiai po dviejų dešimtmečių. Antrojo pasaulinio karo pradžioje 1940 m. Sovietų armija įžengė į Baltijos šalis, dėl ko įvyko Baltijos aneksija ir trijų naujų Sovietų respublikų, kaip Sovietų Sąjungos dalies, paskelbimas. Nacistinė Vokietija užpuolė Sovietų Sąjungą 1941 m., ir nacių okupacija Baltijos šalyse truko nuo 1941 iki 1944 m. 1944 m. Sovietų armija vėl įžengė į Baltijos valstybes, perkeliant Rytų frontą link Vokietijos. Po Antrojo pasaulinio karo Baltijos šalys liko okupuotos ir inkorporuotos į Sovietų Sąjungą beveik 50 metų. Sovietų laikotarpiu Baltijos šalis žymėjo ilgalaikis politinis engimas, kai šimtai tūkstančių žmonių patyrė politinį smurtą, politinį įkalinimą ir priverstinį iškeldinimą. 1990-aisiais Baltijos šalys paskelbė nepriklausomybę, po to sekė įstojimas į ES ir NATO 2004 m.",
      "trauminio_streso_tyrimu_kilimas": "Socialinis ir politinis kontekstas formavo trauminio streso teorijas ir tyrimus Europoje, Baltijos šalys čia nėra išimtis. Baltijos valstybių istorija yra glaudžiai susijusi su trauminio streso srities vystymu šiose šalyse. Psichologija ir psichoterapija kaip profesija ir tyrimų sritis buvo engiama dešimtmečius Sovietų režimo metu. 1980 m., kai potrauminio streso sutrikimo (PTSS) diagnozė buvo įtraukta į Psichikos sutrikimų diagnostikos ir statistikos vadovą III (DSM-III), Baltijos šalyse vis dar vyravo Sovietų režimas, ir jokio traumos ir su stresu susijusių sutrikimų pripažinimo nebuvo įmanoma. Kas dar blogiau, taip pat yra gerai dokumentuota, kad psichiatrija Sovietų Sąjungoje buvo plačiai naudojama kaip engimo sistemos dalis persekioti tuos asmenis, kurie buvo prieš Sovietų režimą.",
      "politinio_smurto_tyrimai": "Psihotraumatologija Baltijos valstybėse buvo grindžiama susidomėjimu politinio smurto ir engimo psichologiniais poveikiais. Vienas pirmųjų PTSS tyrimų buvo paskelbtas 1992 m. netrukus po Lietuvos nepriklausomybės atkūrimo, kurį atliko Griškonytė, Barzdžiukaitė ir Ručinskienė (1992), tiriant potraumines reakcijas klinikinėje 27 Sovietų armijos karinio smurto prieš taikią demonstraciją 1991 m. sausio 13 d. Vilniuje, Lietuvoje, išgyvenusiųjų imtyje. Ilgalaikis 1991 m. \"Kruvinojo sausio\" psichologinis poveikis išgyvenusiems ir žuvusiųjų artimiesiems buvo tyrinėtas 20 metų vėliau kokybiniu tyrimu, kurį atliko Povilaitis ir kt. (2015).",
      "traumos_ir_ptss_paplitimas": "Epidemiologinių duomenų apie psichikos sveikatos sutrikimus Europoje apžvalga atskleidžia 12 mėnesių PTSS paplitimą nuo 1,1 iki 2,9%, su reikšmingu PTSS paplitimo sumažėjimu didėjant amžiui. Keli tyrimai pateikė epidemiologinius duomenis Lietuvoje su pranešta didesnio traumos ir PTSS paplitimo tendencija, palyginti su Europa apskritai. Kazlauskas ir Želvienė (2015) pranešė apie 70% paplitimą bent vieno gyvenimo trauminio įvykio patyrimo Lietuvos bendrojoje populiacijoje, remiantis 626 suaugusiųjų nuo 18 iki 89 metų imtimi. Domanskaite-Gota, Elklit ir Christiansen (2009) pranešė apie 75% trauminių patirčių paplitimą 15 metų amžiaus reprezentatyvioje 183 paauglių iš Lietuvos imtyje ir 7% PTSS paplitimą, remiantis DSM-IV kritėrijais.",
      "nelaimes_tyrimai": "Mažiausiai dvi didelės nelaimės ištiko regioną: Černobylio atominės elektrinės avarija 1986 m. ir MS Estonia laivo katastrofa 1994 m. Černobylio avarija laikoma didžiausia branduoline nelaime pasaulyje. Yra keletas tyrimų apie sveikatos padarinius, mirtingumą ir savižudybės mintis Černobylio nelaimės likvidatorių iš Estijos imtyje, tačiau mažai žinoma apie potrauminius nelaimės padarinius Baltijos šalyse.",
      "raidos_perspektyva": "Baltijos šalyse auga susidomėjimas raidos klausimais, ypač vaikų piktnaudžiavimo tyrimais. Galėjome rasti bent du didelius tarptautinius tyrimus su rezultatais iš Latvijos ir Lietuvos, įtrauktais į vaikų piktnaudžiavimo paplitimo tyrimus. Sebre ir kt. (2004) pranešė apie 1145 paauglių nuo 10 iki 14 metų iš Latvijos, Lietuvos, Makedonijos ir Moldovos tyrimo rezultatus. Tėvų smurtas buvo susijęs su didesniu alkoholio vartojimu, o vaikai iš kaimo vietovių patyrė daugiau smurto.",
      "ateities_kryptys": "Mūsų trumpa apžvalga atskleidžia augantį susidomėjimą trauminiu stresu Baltijos šalyse. Psihotraumatologijos tyrimai yra susiję su specifiniu regiono socio-istoriniu kontekstu, su stipriu susidomėjimu politinio engimo pasekmėmis. Dauguma trauminio streso tyrimų iš Baltijos valstybių yra fundamentalūs, sutelkiant dėmesį į tarpininkavimo veiksnius ir atsparumą. Nors radome keletą įdomių tyrimų iš Baltijos regiono, turėtume pripažinti, kad buvo paskelbta nedaug trauminio streso tyrimų. Trūksta epidemiologinių duomenų, nėra paskelbta PTSS gydymo RCT ar ankstyvos intervencijos tyrimų, ir PTSS neuromokslo tyrimų nėra iš Baltijos valstybių."
    },
    "saltinis": "European Journal of Psychotraumatology 2016, 7: 29295",
    "doi": "http://dx.doi.org/10.3402/ejpt.v7.29295",
    "pdf_file": "2_Istorija_Trauma research in the Baltic countries-1.pdf"
  },
  {
    "id": 2,
    "pavadinimas": "Holokausto tarpkartinės pasekmės palikuonių psichinei sveikatai: sisteminė susijusių veiksnių ir mechanizmų apžvalga",
    "autoriai": "Patricia Dashorst, Trudy M. Mooren, Rolf J. Kleber, Peter J. de Jong & Rafaele J. C. Huntjens",
    "institucija": "Stichting Centrum'45/partner in Arq, Nyderlandai; Klinikinės ir sveikatos psichologijos katedra, Utrechto universitetas, Nyderlandai; Klinikinės psichologijos ir eksperimentinės psichopatologijos katedra, Groningeno universitetas, Nyderlandai",
    "metai": 2019,
    "santrauka": "Karas ir smurtas turi didžiulių pasekmių visai visuomenei, žalingą poveikį žmonių individualiam gyvenimui ir gali turėti tarpkartines pasekmes. Norint geriau suprasti šias tarpkartines pasekmes, Holokausto poveikio palikuonims tyrimai yra svarbus informacijos šaltinis. Šio tyrimo tikslas buvo sistemingai apžvelgti tarpkartinių pasekmių mechanizmus, apibendrinti Holokausto išgyvenusiųjų ir jų palikuonių charakteristikas, kurios gali turėti įtakos palikuonių psichinei sveikatai. Dėmesį sutelkėme į: 1) tėvų psichikos sveikatos problemas, 2) (suvokiamą) auklėjimą ir prisirišimo kokybę, 3) šeimos struktūrą, ypač tėvų Holokausto istoriją, 4) papildomą stresą ir gyvenimo įvykius, ir 5) tarpkartinio perdavimo psichofiziologinius procesus. Nustatėme 23 tinkamus tyrimus, paskelbtus tarp 2000 ir 2018 metų. Tik Holokausto išgyvenusiųjų tyrimai atitiko įtraukimo kriterijus. Nustatyta, kad įvairios tėvų ir vaikų charakteristikos bei jų sąveika prisideda prie psichologinių simptomų bei biologinių ir epigenetinių pokyčių vystymosi. Tėvų psichikos sveikatos problemos, suvokiamas auklėjimas, prisirišimo kokybė ir tėvų lytis atrodė įtakojantys palikuonių psichinę gerovę. Be to, turėjimas dviejų išgyvenusiųjų tėvų lėmė didesnes psichikos sveikatos problemas, palyginti su vieno išgyvenusiojo tėvo turėjimu. Taip pat buvo įrodymų, kad Holokausto išgyvenusiųjų palikuonys rodo didesnį pažeidžiamumą stresui, nors tai buvo akivaizdu tik akivaizdžios grėsmės akivaizdoje. Galiausiai, rezultatai taip pat rodo tarpkartines pasekmes palikuonių kortizolio lygiams. Aptariamos klinikinės ir gydymo implikacijos.",
    "raktiniai_zodziai": ["Holokaustas", "tarpkartinis", "trauma", "palikuonys"],
    "turinys": {
      "ivadinė_dalis": "Karas ir smurtas buvo žmonijos istorijos dalis. Šiandien daugiau nei 65 milijonai žmonių visame pasaulyje buvo priversti palikti namus dėl ginkluotų konfliktų; daugiau nei 21 milijonas jų yra pabėgėliai, iš kurių daugiau nei pusė yaunesni nei 18 metų. Karas ir smurtas turi ne tik didžiulių pasekmių visai visuomenei, bet ir žalingą poveikį žmonių individualiam gyvenimui. Be su trauma susijusios psichopatologijos tiems, kurie buvo paveikti, smurtas ir karas taip pat gali turėti tarpkartinių pasekmių. Terminas 'trauma perdavimas' buvo naudojamas apibūdinti šias pasekmes, apibrėžtas kaip mintys, jausmai ir elgesys, atsiradę iš išgyvenusiųjų patirčių ir perduoti jų palikuonims.",
      "tyrimo_tikslai": "Šios sisteminės apžvalgos tikslas buvo padidinti mūsų supratimą apie (masinio) smurto tarpkartines pasekmes, nagrinėjant galimus mechanizmus, kurie yra susiję ir gali prisidėti prie Antrojo pasaulinio karo ir konkrečiai Holokausto išgyvenusiųjų palikuonių psichikos sveikatos problemų vystymosi. Konkrečiai, buvo įvertinti penki galimi mechanizmai, kurie buvo nustatyti remiantis teoriniais ir empiriniais tyrimais kaip veiksniai, galintys atlikti lemiamą vaidmenį Holokausto išgyvenusiųjų palikuonių psichikos sveikatai.",
      "tėvų_psichikos_sveikata": "Sunkūs psichikos sutrikimai gali paveikti ne tik tuos, kurie jais serga, bet ir tuos, kurie yra artimame asmeniniame kontakte su jais. Pavyzdžiui, tėvai, turintys sunkų nerimą ir/arba depresiją, gali modeliuoti mąstymo, jausmų ir elgesio schemas savo vaikams. Žemas savivertės jausmas, nepasitikėjimas kitais žmonėmis ir pesimistiškas požiūris į pasaulį apskritai ir į ateitį gali būti pagrindinis žinutė, perduodama jų palikuonims. Todėl iškėlėme hipotezę, kad didesnis dabartinių ir gyvenimo psichikos sveikatos problemų bei psichiatrinių diagnozių dažnis Holokausto išgyvenusiųjų tarpe yra susijęs su didesniu psichikos sveikatos problemų dažniu HSO (Holokausto išgyvenusiųjų palikuonims).",
      "auklėjimas_ir_prisirišimas": "Prisirišimo teorija numato auklėjimą, kuris yra atsakingas ir pritaikytas prie jauno vaiko poreikių, kad jis augtų, klestėtų ir tirtų pasaulį. Tėvai, kurie turi spręsti neišspręstas problemas iš savo praeities, pavyzdžiui, netektį ar blogo elgesio, gali turėti sunkumų prisitaikydami prie savo palikuonių poreikių, tai daro įtaką tėvų ir vaikų sąveikos kokybei. Tėvai gali, pavyzdžiui, rodyti išsigandusį, bauginantį ar netikėtą elgesį, kai asocijuoja stresines situacijas savo dabartiniame gyvenime su traumine patirtimi praeityje. Ši auklėjimo praktika arba tėvų ir vaiko santykių dinamika gali, savo ruožtu, būti dezorganizuoto prisirišimo pagrindas ir prisidėti prie palikuonių psichikos sveikatos problemų.",
      "tėvų_holokausto_istorija": "Dėl šeimos narių nebuvimo dėl Holokausto, palikuonys galėjo turėti mažiau šeimos paramos, palyginti su ne-Holokausto palikuonimis. Be to, išgyvenę tėvai galėjo būti mažiau pajėgūs teikti tiesioginę ir netiesioginę priežiūrą, pavyzdžiui, veikti kaip tinkamas vaidmens modelis arba teikti emocinę paramą ir patarimus. Vaikai iš vieno išgyvenusiojo šeimų (t.y., kai kitas tėvas gyvas ir ne išgyvenęs) gali būti geresnėje padėtyje, palyginti su vaikais iš dviejų išgyvenusiųjų šeimų, nes neišgyvenęs tėvas gali papildyti kai kurias užduotis, kurios yra sunkios išgyvenusiam tėvui.",
      "papildomas_stresas": "Keli autoriai pasiūlė diatezės-streso modelį, kuris numato didesnį pažeidžiamumą HSO stresiniams gyvenimo įvykiams, kurie įvyksta vėliau gyvenime. Kitaip tariant, HSO gali rodyti padidėjusį pažeidžiamumą plėtoti psichologinius sutrikimus, kai paveikia rimti fiziniai ar psichologiniai stresoriai, papildantys šeimos Holokausto patirtis, pavyzdžiui, krūties vėžys arba kovos patirtis. Todėl iškėlėme hipotezę, kad HSO kenčia nuo daugiau psichikos sveikatos problemų dėl kaupiamųjų neigiamų gyvenimo įvykių nei neišgyvenusiųjų palikuonys.",
      "biologiniai_veiksniai": "Be psichologinių mechanizmų, siejančių tėvų traumą ir palikuonių psichinį distresą, poveikio, vis didesnis tyrimų skaičius atsižvelgė į biologinius ir (epi)genetinius mechanizmus, siejančius tėvų traumą su pokyčiais palikuonių kortizolio metabolizme, palyginti su netraumizuotų tėvų palikuonimis. Vis labiau aišku, kad tėvų stresas, prenataliniame ar postnataliniame laikotarpyje, veikia palikuonių streso sistemą, sukeliant epigenetinius ir kortizolio lygio pokyčius.",
      "išvados": "Ši trumpa apžvalga atskleidžia augantį susidomėjimą trauminiu stresu, susijusį su Holokaustu. Psihotraumatologijos tyrimai yra susiję su specifiniu regiono socio-istoriniu kontekstu, su stipriu susidomėjimu politinio engimo pasekmėmis. Dauguma trauminio streso tyrimų iš Holokausto išgyvenusiųjų yra fundamentalūs, sutelkiant dėmesį į tarpininkavimo veiksnius ir atsparumą. Bendrai, nustatėme, kad tarpkartines pasekmes geriausia suprasti per kelių veiksnių poveikį (ir sąveiką), o ne vieno veiksnio, lemiančio psichikos sveikatos rezultatus palikuonims."
    },
    "saltinis": "European Journal of Psychotraumatology 2019, 10:1, 1654065",
    "doi": "https://doi.org/10.1080/20008198.2019.1654065",
    "pdf_file": "7_Trauma tarp kartu_Dashorst et al..pdf"
  },
  {
    "id": 3,
    "pavadinimas": "Potrauminis augimas: koncepciniai pagrindai ir empiriniai įrodymai",
    "autoriai": "Richard G. Tedeschi ir Lawrence G. Calhoun",
    "institucija": "Šiaurės Karolinos universitetas Šarlotėje, JAV",
    "metai": 2004,
    "santrauka": "Šis straipsnis aprašo potrauminio augimo koncepciją, jos konceptualius pagrindus ir palaikančius empirinius įrodymus. Potrauminis augimas yra teigiamų pokyčių patyrimas, atsirandantis dėl kovos su labai sudėtingomis gyvenimo krizėmis. Jis pasireiškia įvairiais būdais, įskaitant padidėjusį gyvenimo vertinimą apskritai, prasmingesnius tarpasmeninius santykius, padidėjusį asmeninės jėgos jausmą, pasikeitusias prioritetus ir turtingesnį egzistencinį bei dvasinį gyvenimą. Nors terminas naujas, idėja, kad iš didžio kančių gali kilti didelis gėris, yra senovinė. Mes siūlome modelį, skirtą potrauminio augimo procesui suprasti, kuriame individualios charakteristikos, parama ir atskleidimas bei, svarbiausia, reikšmingas kognityvinis apdorojimas, apimantis trauminio įvykio pažeistas ar paneigintas kognityvines struktūras, atlieka svarbų vaidmenį. Taip pat siūloma, kad potrauminis augimas sąveikauja su gyvenimo išmintimi ir gyvenimo pasakojimo plėtojimu bei kad tai yra nuolatinis procesas, o ne statiškas rezultatas.",
    "raktiniai_zodziai": ["Potrauminis augimas", "trauma", "atsigavimas", "atsparumas", "kognityvinis apdorojimas"],
    "turinys": {
      "ivadinė_dalis": "Šio straipsnio tikslas – aprašyti potrauminio augimo koncepciją, jos konceptualius pagrindus ir palaikančius empirinius įrodymus. Žmonės, susidūrę su didelėmis gyvenimo krizėmis, dažnai praneša apie teigiamus pokyčius, kurie kilo iš jų kovos su šiais iššūkiais. Nors traumos ir krizės yra giliai trikdančios, jos taip pat gali būti teigiamų transformacijų katalizatoriai.",
      "neigiamos_reakcijos": "Žmonės, susidūrę su didelėmis gyvenimo krizėmis, paprastai patiria nerimą keliančias emocijas. Ypač aplinkybėms, grasinančioms asmens fizinei gerovei, būdingas nerimas ar specifinės baimės. Liūdesys ir depresija gali būti įprasta reakcija į gyvenimo krizes. Kaltė, pyktis ir bendras dirglumas yra kiti afektiniai atsakai, dažnai stebimi žmonėms, kovojantiems su reikšmingomis gyvenimo problemomis. Gali būti nustatyti neraminantys ir kartais disfunkciniai mąstymo modeliai. Dėl staigių ir netikėtų įvykių būdinga pradinė netikėjimo reakcija ir psichologinio sustingimo patyrimas.",
      "pozityvūs_aspektai": "Bendras supratimas, kad kančia ir negandos gali būti teigiamų pokyčių šaltinis, yra tūkstančių metų senumo. Pavyzdžiui, kai kurios ankstyvosios hebrajų, graikų ir ankstyvųjų krikščionių idėjos bei raštai, taip pat kai kurie induizmo, budizmo ir islamo mokymai, apima kančios transformuojančią galią. XX amžiuje keli klinikai ir mokslininkai, rašantys psichologijos srityje, ėmėsi svarstyti būdus, kaip kritinės gyvenimo krizės suteikė galimybę teigiamam asmeniniam pokyčiui.",
      "augimo_sritys": "Potrauminio augimo klausimynas (PTGI) išskiria penkias pagrindines potrauminio augimo sritis: didesnis gyvenimo vertinimas ir pasikeitęs prioritetų jausmas; šiltesni, artimesni santykiai su kitais; didesnis asmeninės jėgos jausmas; naujų galimybių ar gyvenimo kelių atpažinimas; dvasinis vystymasis. Padidėjęs gyvenimo vertinimas apskritai ir daugelis mažesnių jo aspektų, kartu su pasikeitusiu suvokimu, kas yra svarbu, yra bendras elementas daugelio žmonių, kovojusių su dideliais sunkumais, patyrime.",
      "procesas": "Augimas, tačiau, nevyksta kaip tiesioginis traumos rezultatas. Tai individo kova su nauja tikrove po traumos, kuri yra esminė nustatant, kiek įvyks potrauminis augimas. Mes naudojome žemės drebėjimo metaforą šiam procesui aprašyti. Psichologiškai seisminis įvykis gali stipriai supurtyti, grasinti ar paversti griuvėsiais daugelį scheminių struktūrų, kurios vadovavo supratimui, sprendimų priėmimui ir prasminumui. Psichologinė krizė gali būti apibrėžta pagal tai, kiek pagrindiniai prielaidų pasaulio komponentai yra meta iššūkis.",
      "kognityvinis_apdorojimas": "Kognityvinis krizės įvykių apdorojimas turi labai emocinį elementą, susietą su juo. Kas daro šias patirtis transformuojančiomis, atrodo, yra tai, kad jos turi šį afektinį komponentą, todėl išmoktos pamokos nėra tik intelektinės refleksijos. Potrauminis augimas greičiausiai yra psichologinio išlikimo bandymų pasekmė, ir jis gali egzistuoti kartu su likusiu traumos distresu. Beveik visi, pranešantys apie potraumitį augimą, taip pat pripažįsta bent šiek tiek distreso.",
      "socialinė_parama": "Palaikantys kiti gali padėti potrauminio augimo procese, suteikdami būdą kurti pasakojimus apie įvykusius pokyčius ir siūlydami perspektyvas, kurios gali būti integruotos į schemos keitimą. Mes pabrėžėme ypač svarbų abipusės paramos vaidmenį, nes tų, kurie 'ten buvo', patikimumas gali būti lemiamas nustatant traumos išgyvenusiųjų norą įtraukti naujas perspektyvas ar schemas.",
      "išvados": "Potrauminio augimo pranešimai dabar gerai dokumentuoti, ir šis psichologinių reakcijų į dideles gyvenimo krizes aspektas turėtų būti reguliariai integruojamas į tyrimus šioje srityje. Reiškinys yra sudėtingas ir negali būti lengvai redukuotas tiesiog į įveikos mechanizmą, pažinimo iškraipymą, psichologinį prisitaikymą ar gerovę, ar daugybę akivaizdžiai panašių konstrukcijų. Potrauminio augimo rezultatai geriausiai galėtų būti laikomi iteratyviniais, ir reikės ilgalaikio darbo, kad būtų galima atsekti įvairias potrauminio augimo proceso trajektorijas."
    },
    "saltinis": "Psychological Inquiry 2004, 15:1, 1-18",
    "doi": "https://doi.org/10.1207/s15327965pli1501_01",
    "pdf_file": "8_Posttraumatic Growth Conceptual Foundations and Empirical Evidence, Tedeschi and Calhoun.pdf"
  },
  {
    "id": 4,
    "pavadinimas": "Psichoterapijos metodai PTSS gydymui: kas jiems bendra?",
    "autoriai": "Ulrich Schnyder, Anke Ehlers, Thomas Elbert, Edna B. Foa, Berthold P. R. Gersons, Patricia A. Resick, Francine Shapiro ir Marylène Cloitre",
    "institucija": "Įvairios institucijos: Ciuricho universiteto ligoninė (Šveicarija), Oksfordo universitetas (JK), Konstanco universitetas (Vokietija), Pensilvanijos universitetas (JAV), Amsterdamo universitetas (Nyderlandai), Duke universitetas (JAV), Mentalinių tyrimų institutas (JAV), Nacionalinis PTSS centras (JAV)",
    "metai": 2015,
    "santrauka": "Per pastaruosius tris dešimtmečius trauminio streso srities tyrimai ir klinikinė praktika išsivystė nepaprastai. Lygiagrečiai su nuosekliu bazinių žinių kaupimusi buvo sukurti terapiniai metodai žmonėms, kenčiantiems nuo potrauminio streso sutrikimo (PTSS) ir kitų su trauma susijusių psichologinių problemų, gydyti. Šiandien yra keletas įrodymais pagrįstų gydymo būdų. Jie skiriasi įvairiais būdais, tačiau taip pat turi nemažai bendrumų. Tokioje situacijoje klinikai gali stebėtis, kurią gydymo programą naudoti arba, konkrečiau, kurie gydymo komponentai yra kritiški sėkmingai terapijai. Šiame straipsnyje septyni pionieriai, sukūrę empiriškai pagrįstus psichoterapijos metodus traumos sukeltiems sutrikimams, buvo paprašyti parašyti esė iš trijų dalių: pirma, pateikti trumpą jų sukurto gydymo santrauką; antra, nustatyti tris pagrindinius bendrus ir kritinius intervencijas gydant PTSS; ir trečia, pasiūlyti svarbias temas ir būsimus tyrimo kryptis. Straipsnis baigiamas santrauka, išryškinančia nustatytus bendrumus (psichoedukacija; emocijų reguliavimas ir įveikos įgūdžiai; vaizduotės ekspozicija; kognityvinis apdorojimas, restruktūrizavimas ir/arba prasmės kūrimas; emocijos; ir atminties procesai), nurodant būsimas kryptis, tokias kaip bandymas geriau suprasti veiksmo mechanizmus ir kurti gydymą, pritaikytą skirtingų pacientų grupių poreikiams.",
    "raktiniai_zodziai": ["Psihotraumatologija", "Potrauminis streso sutrikimas", "Kompleksinis PTSS", "Psichoterapija", "Ekspozicija", "Kognityvinis restruktūrizavimas", "Psichoedukacija"],
    "turinys": {
      "ivadinė_dalis": "Per pastaruosius 3 dešimtmečius trauminio streso srities tyrimai ir klinikinė praktika išsivystė nepaprastai. Lygiagrečiai su nuosekliu bazinių žinių kaupimusi buvo sukurti terapiniai metodai žmonėms, kenčiantiems nuo potrauminio streso sutrikimo (PTSS) ir kitų su trauma susijusių psichologinių problemų, gydyti. Šiandien yra keletas įrodymais pagrįstų gydymo būdų. Jie skiriasi įvairiais būdais, įskaitant sesijų trukmę ir skaičių, taip pat intervencijų skaičių ir įvairovę. Kai kurios gydymo programos orientuojasi į in vivo ekspoziciją grėsmės stimulams, o kitos sutelkia dėmesį į įvykio pervertinimą, nereikalaujant tiesioginio susidūrimo su su grėsme susijusiais stimulais.",
      "gydymo_metodai": "Straipsnyje pristatomi septyni pagrindiniai įrodymais pagrįsti PTSS gydymo metodai: 1) STAIR nartyvo terapija (Marylène Cloitre) - sutelkta į emocijų reguliavimo ir tarpasmeninių įgūdžių mokymą kartu su traumos naratyvo analize. 2) Kognityvinė terapija PTSS (Anke Ehlers) - apima penkias pagrindines gydymo procedūras, įskaitant individualizuotos atvejo formuluotės kūrimą, traumos atsiminimų atnaujinimą, diskriminavimo mokymą ir nenaudingų elgesio būdų atsisakymą. 3) Naratyvinės ekspozicijos terapija (Thomas Elbert) - sutelkta į patirtis su stipriausiomis aktyvacijos reakcijomis ir chronologiškai konstruoja gyvenimo istoriją. 4) Ilgalaikės ekspozicijos terapija (Edna Foa) - susideda iš keturių komponentų, iš kurių du yra pagrindiniai: įsivaizduojama ekspozicija ir nuolatinis artėjimas prie vengiamų, saugių su trauma susijusių situacijų. 5) Trumpoji eklektinė psichoterapija PTSS (Berthold Gersons) - jungia penkis modulius iš skirtingų kilmių, pradedant psichoedukacija kartu su partneriu. 6) Kognityvinio apdorojimo terapija (Patricia Resick) - apima švietimą, kognityvinę terapiją dėl klaidingų įsitikinimų apie traumą ir traumos pasakojimą. 7) EMDR terapija (Francine Shapiro) - išsamus aštuonių fazių požiūris, pabrėžiantis atminties ir informacijos apdorojimo sistemos vaidmenis.",
      "bendri_elementai": "Visi šiuolaikiniai įrodymais pagrįsti psichoterapijos metodai traumos išgyvenusiems žmonėms turi daug bendrumų. Autorių nustatyti bendrumai apima: 1) Psichoedukacija - siūlo informaciją apie potrauminio streso reakcijų pobūdį ir eigą, nustato būdus, kaip susidoroti su traumos priminimais, ir aptaria strategijas, kaip valdyti distresą. 2) Emocijų reguliavimas ir įveikos įgūdžiai - dažnai mokomi ir treniruojami įvairiuose terapiniuose požiūriuose. 3) Įsivaizduojama ekspozicija - stipriai pabrėžiama PE ir NET metoduose, tačiau tam tikra ekspozicijos forma pacientų traumos atminčiai gali būti randama beveik visuose įrodymais pagrįstuose psichoterapijos metoduose traumos sukeltiems sutrikimams. 4) Kognityvinis apdorojimas, restruktūrizavimas ir/arba prasmės kūrimas - dar vienas elementas, kurį galima rasti beveik visuose empiriškai pagrįstuose psichologiniuose PTSS gydymo metoduose. 5) Emocijos - taikomos visose psichoterapijose. 6) Atminties procesai - taip pat atlieka svarbų vaidmenį gydant su trauma susijusius sutrikimus.",
      "ateities_kryptys": "Daugelis autorių pasiūlė, kad dėmesys turėtų būti skiriamas pogydomio liekamųjų simptomų ir pažeidžiamumo naujų trauminių įvykių klausimui. Reikalingas geresnis veikimo mechanizmų supratimas. Toks sisteminis tyrimas gali padėti nustatyti efektyviausius gydymo elementus, kad terapijos galėtų tapti galingesnės ir supaprastintos. Be to, mechanizmų tyrimas taip pat gali padėti nustatyti procesus ar mechanizmus, kurie buvo praleisti ir kurie gali žymiai paveikti rezultatus. Taip pat rekomenduojama kurti gydymą, pritaikytą skirtingų pacientų grupių poreikiams, atsižvelgiant į tokius veiksnius kaip amžius, lytis, kultūra, komorbidiškumas ir traumos patirties tipas.",
      "išvados": "Šiuo metu prieinami empiriškai pagrįsti psichoterapijos metodai traumos išgyvenusiems žmonėms turi daug bendrumų. Net ir turint šiuos apribojimus, straipsnyje apžvelgtos terapijos - kiekviena su savo skirtingu dėmesiu - visos buvo įrodytos esančios efektyvios, suteikdamos klinikams įvairių empiriškai pagrįstų gydymo pasirinkimų, kad jie galėtų padėti savo pacientams. Tikimės, kad bendri elementai, nustatyti šiame straipsnyje kaip kritiniai gydant PTSS, tarnaus kaip gairė būsimam vystymuisi, palaikydami klinikus jų nuolatiniuose bandymuose teikti geriausią įmanomą su trauma susijusią psichoterapiją savo pacientams."
    },
    "saltinis": "European Journal of Psychotraumatology 2015, 6: 28186",
    "doi": "https://dx.doi.org/10.3402/ejpt.v6.28186",
    "pdf_file": "9_Pagalbos budai PTSS_Schnyder et al..pdf"
  },
  {
    "id": 5,
    "pavadinimas": "Sveikatos priežiūros teikimo traumuotoms populiacijoms iššūkiai: PTSS gydymo kliūtys ir naujų sprendimų poreikis",
    "autoriai": "Evaldas Kazlauskas",
    "institucija": "Klinikinės ir organizacinės psichologijos katedra, Vilniaus universitetas, Vilnius, Lietuva",
    "metai": 2017,
    "santrauka": "Pasaulyje vis labiau pripažįstamas traumatinių patirčių poveikis psichinei sveikatai. Su vykstančiais konfliktais, stichinėmis nelaimėmis, tarpasmeniniais smurtu ir kitais traumatiniais įvykiais apskaičiuojama, kad maždaug 70% pasaulio gyventojų yra patyrę bent vieną gyvenimo traumatinę patirtį. Tyrimai rodo, kad didelė dalis išgyvenusiųjų, ypač žemų ir vidutinių pajamų šalyse, turėtų potrauminio streso sutrikimą (PTSS). Per pastaruosius dešimtmečius buvo sukurti efektyvūs įrodymais pagrįsti PTSS gydymo būdai. Tačiau yra reikšmingų kliūčių prieigai prie psichikos sveikatos paslaugų, ir su trauma susiję gydymo būdai nėra lengvai prieinami traumos išgyvenusiesiems. Socialinės psihotraumatologijos perspektyvoje buvo nustatytos kelios pagrindinės kliūtys traumos gydymui, įskaitant pripažinimo trūkumą ir atskleidimo vengimą. PTSS gydymo kultūrinio jautrumo poreikis, alternatyvūs gydymo teikimo būdai ir neprofesionalių savanorių įtraukimas siūlomi kaip būsimo vystymo kryptys šioje srityje.",
    "raktiniai_zodziai": ["Trauma", "Kliūtys", "Pasaulinė psichikos sveikata", "PTSS"],
    "turinys": {
      "ivadinė_dalis": "Net ir norėdami, kad mūsų pasaulis būtų saugus ir patikimas, traumatinės patirtys yra neišvengiamos žmogaus egzistencijos palydovės. Tyrimai rodo, kad dauguma gyventojų per gyvenimą patiria traumatinių įvykių, ir tai tiesa visame pasaulyje. Neseniai atliktas epidemiologinis tyrimas atskleidė, kad net aukštų pajamų šalyse, tokiose kaip Jungtinės Amerikos Valstijos, 95% gyventojų patyrė bent vieną gyvenimo traumatinį įvykį, ir apie 70% europiečių patiria traumatines patirtis. Tyrimai taip pat demonstruoja pastebimą atsparumą įveikiant traumatines patirtis. Dauguma išgyvenusiųjų sėkmingai įveikia traumatines patirtis, naudodamiesi vidiniais ištekliais ir socialine parama iš savo socialinio tinklo.",
      "ptss_našta": "Kai kurie išgyvenusieji gali turėti sunkių prisitaikymo sutrikimų po traumatinių įvykių. Nuo potrauminio streso sutrikimo (PTSS) įtraukimo į Diagnostinį ir statistinį sutrikimų vadovą (DSM-III) 1980 m., PTSS dabar tapo viena iš dažniausių diagnozių tarp psichikos sveikatos specialistų. Vis dėlto turime gana ribotas žinias apie PTSS paplitimą visame pasaulyje. Remiantis epidemiologiniais skaičiavimais, 12 mėnesių PTSS paplitimas gali svyruoti nuo 1% iki 38% skirtingose šalyse. Naujausi skaičiavimai rodo, kad PTSS paplitimas per pastaruosius 12 mėnesių svyravo nuo 1,1% iki 2,9% skirtingose amžiaus grupėse Europoje. Su maždaug pusės milijardo gyventojų, galime nustatyti, kad bent 5 milijonai žmonių Europoje turi PTSS. O šalyje, kurioje vyksta konfliktas, PTSS paplitimas bendrojoje populiacijoje gali siekti net 38%, tai rodo, kad pasaulyje yra milijonai išgyvenusiųjų su PTSS.",
      "efektyvus_gydymas": "PTSS turi didelę kainą visuomenėms ir yra pasaulinis poreikis efektyviam PTSS gydymui. Per pastaruosius keletą dešimtmečių buvo sukurta keletas įrodymais pagrįstų PTSS gydymo būdų. Tačiau šie gydymo būdai buvo daugiausia sukurti ir išbandyti aukštų pajamų šalyse (JAV, Kanadoje ir Europoje). Efektyvūs gydymo būdai, tokie kaip su trauma susijusi kognityvinė elgesio terapija (TF-CBT) arba akių judesių desensibilizacija ir reprocesavimas (EMDR), nors turi stiprius efektyvumo įrodymus, nebuvo tinkamai išbandyti daugiakultūriniame pasauliniame kontekste.",
      "kliūtys_gydymui": "Gydymo atotrūkis psichikos sveikatos srityje yra pasaulinis. Remiantis naujausiais trauminio streso tyrimų srities atradimais, buvo nustatytos kelios pagrindinės kliūtys efektyvių PTSS gydymo būdų sklaidai ir teikimui traumuotoms populiacijoms, svarbios sveikatos priežiūros politikai: 1) Išgyvenusiųjų pripažinimas - daugelyje kultūrų traumos išgyvenusieji gali patirti stigmatizaciją ir pripažinimo trūkumą. Neigiamai veikiantis socialinio pripažinimo trūkumas buvo pademonstruotas keliuose neseniai atliktuose tyrimuose. Neigiami požiūriai į traumos išgyvenusiuosius visuomenėje sukelia vengiantį pagalbos ieškojimo elgesį. 2) Vengimas ir traumos atskleidimas - vienas iš pagrindinių PTSS simptomų yra vengimas. Išgyvenusieji su PTSS simptomais labai dažnai vengia traumatinių patirčių atskleidimo. 3) Riboti ištekliai - įrodymai rodo, kad psichologinis gydymas traumos išgyvenusiesiems yra efektyviausias PTSS gydymas. Tačiau reikalingi kvalifikuoti gydytojai ar psichologai, turintys mokymą su trauma susijusiuose gydymo būduose. 4) Vykstantys konfliktai ir nelaimės - labai sunku teikti PTSS gydymą šalyje, kurioje vyksta konfliktas ar net karas.",
      "ateities_kryptys": "Todėl siūlomos kelios būsimų krypčių trauminio streso srities tyrimams, kurios yra svarbios nacionaliniam ir tarptautiniam sveikatos priežiūros vystymuisi, ir galėtų prisidėti prie negydyto PTSS atotrūkio mažinimo traumuotose populiacijose: 1) Kultūrinis jautrumas - turime nemažai įrodymų apie tarpkultūrinį PTSS diagnozės pagrįstumą. Tačiau reikalingas kultūrinis jautrumas PTSS gydyme. Reikalingi daugiau tarpkultūrinių tyrimų, kad būtų patvirtintas PTSS gydymo efektyvumas šalyse už aukštų pajamų šalių Šiaurės Amerikoje ir Europoje ribų. 2) Alternatyvūs sveikatos priežiūros modeliai - vis daugiau tyrimų teikia įrodymus, kad internetu grįstos intervencijos gali būti panašiai efektyvios kaip tradicinis akis į akį gydymas. Pasaulinės E-klinikų vystymo iniciatyvos su internetiniais daugiakalbiais vertinimais ir gydymo moduliais galėtų palengvinti prieigą prie įrodymais pagrįstų PTSS gydymo būdų. 3) Neprofesionalių savanorių įtraukimas - artimoje ateityje neturėsime pakankamai prieinamų apmokyti specialistų įrodymais pagrįstuose traumos gydymo būduose visame pasaulyje. Turime peržiūrėti savo psichikos sveikatos priežiūros teikimo koncepcijas ir panaudoti savanorius ir kitus ne specialistus.",
      "išvados": "Traumatinių įvykių ir PTSS našta bei kaina didėja. Šiame straipsnyje buvo nustatytos tik kelios kliūtys traumos gydymui, ir buvo pasiūlytos kelios kryptys, pagrįstos dabartiniu trauminio streso tyrimų srities statusu. Sveikatos priežiūros politikos formuotojai turėtų būti informuoti apie socialinių PTSS veiksnių vaidmenį, pavyzdžiui, išgyvenusiųjų socialinio pripažinimo svarbą. Tačiau tarptautinių organizacijų, tokių kaip Pasaulio sveikatos organizacija (PSO), aktyvus vaidmuo taip pat yra labai svarbus įtakojant sveikatos priežiūros politiką regioniniu ir nacionaliniu lygiu. Su didėjančiu įrodymų kiekiu apie išgyvenusiųjų atsparumą ir su trauma susijusių gydymo būdų efektyvumo atradimais, galime tikėtis, kad teigiami pokyčiai yra įmanomi artimoje ateityje įveikiant kliūtis su trauma susijusių sutrikimų gydymui."
    },
    "saltinis": "Global Health Action 2017, 10: 1322399",
    "doi": "https://doi.org/10.1080/16549716.2017.1322399",
    "pdf_file": "10_Pagalbos budai ir issukiai_Kazlauskas.pdf"
  },
  {
    "id": 6,
    "pavadinimas": "Psichologinės potrauminio streso sutrikimo teorijos",
    "autoriai": "Chris R. Brewin ir Emily A. Holmes",
    "institucija": "Klinikinės sveikatos psichologijos padalinys, Londono universiteto koledžas, Londonas, JK; Trauminio streso klinika, Londonas, JK; MRC Pažinimo ir smegenų mokslų skyrius, Kembridžas, JK",
    "metai": 2003,
    "santrauka": "Šiame straipsnyje apibendrinami naujausi tyrimai apie psichologinius procesus, susijusius su potrauminiu streso sutrikimu (PTSS), padedant įvertinti teorinius sutrikimo modelius. Po kelių ankstyvųjų požiūrių, įskaitant socialinį-kognityvinį, sąlygojimo, informacijos apdorojimo ir nerimastingo lūkesčio modelius, straipsnyje pateikiama lyginamoji analizė ir trijų naujausių teorijų vertinimas: Foa ir Rothbaum emocinės apdorojimo teorija; Brewin, Dalgleish ir Joseph dvigubos reprezentacijos teorija; Ehlers ir Clark kognityvinis modelis. Apžvelgiame empirinius įrodymus, susijusius su kiekvienu modeliu, ir nustatome perspektyvias tolesnių tyrimų sritis.",
    "raktiniai_zodziai": ["Potrauminis stresas", "Kognicija", "Emocijos", "Atmintis", "Terapija"],
    "turinys": {
      "ivadinė_dalis": "Oficialus potrauminio streso sutrikimo (PTSS) pripažinimas DSM-III (Amerikos psichiatrų asociacija, 1980) paskatino dabar labai didelį tyrimų kiekį apie šios būklės psichologiją, biologiją, epidemiologiją ir gydymą. Kartu su žinių augimu buvo sukurtos vis sudėtingesnės teorijos, kurios mėgino neatsilikti nuo naujų atradimų, tuo pat metu išlikdamos įsitvirtinusios pagrindinių psichologinių tyrimų srityse. Šiame straipsnyje mes pirmiausia trumpai apžvelgiame dabartines žinias apie PTSS, išskiriant tas sritis, kurios laikomos didžiausios teorinės reikšmės. Tada pateikiame ankstyvųjų sutrikimo teorijų, kurios įtakojo dabartinį mąstymą, apžvalgą, įskaitant socialines-kognityvines, sąlygojimo, informacijos apdorojimo ir nerimastingo lūkesčio teorijas. Pagrindinėje straipsnio dalyje pristatome tris naujesnes teorijas, kurios šiuo metu yra tyrimų dėmesio centre: Emocinės apdorojimo teoriją (Foa & Riggs, 1993; Foa & Rothbaum, 1998), dvigubos reprezentacijos teoriją (Brewin, 2001, spaudoje; Brewin, Dalgleish, & Joseph, 1996); Ehlers ir Clark (2000) kognityvine teoriją. Kiekviena teorija aprašoma detaliai ir apibendrinti svarbūs empiriniai tyrimai. Paskutinėje straipsnio dalyje diskutuojama apie tai, kur teorijos sutaria arba nesutaria, ir kokios, atrodo, yra skubiausios tolesnių tyrimų sritys.",
      "atmintis_ir_ptss": "PTSS buvo nustatyti keletas atminties funkcijų pokyčių, kurie yra palyginami su depresijos pacientų tyrimais: linkstama į padidėjusį su trauma susijusios medžiagos atsiminimą ir sunkumus atsimenant konkrečių įvykių autobiografines atmintis. Labiau specifinė PTSS yra prieštaringa atsiminimo schema, susijusi su pačia traumine medžiaga, panaši į tą, kuri randama emocijų ir atminties tyrimuose su nekliniki nėmis imtimis: kai kuriuose tyrimuose aukštas emocijų lygis siejamas su ryškesnėmis ir ilgiau išliekančiomis atmintimis, o kituose - su miglotomis atmintimis, kuriose trūksta detalių ir kurios linkusios į klaidas. DSM-IV aprašo PTSS kaip pasižymintį tiek dažnais, kančią keliančiais, įkyriais prisiminimais, tiek amnezija įvykio detalėms. Su tuo dera klinikiniai tyrimai ir pastebėjimai, pranešantys, kad painiava ir užmiršimas yra lygiai tiek pat tipiški traumų atminčiai, kiek ir ryškus, ilgalaikis atsiminimas. Sistematiškesni pacientų asmeniškai patirtų trauminių įvykių atminčių tyrimai patvirtina, kad atsiminimas linkęs gerėti per pirmas kelias savaites, kad jų turinys gali keistis, ir kad jie linkę būti neorganizuoti ir turėti spragų.",
      "flashbackai": "Kita išskirtinė PTSS atminties ypatybė yra išgyvenimo patirtys arba 'flashbackai' į traumą. Palyginti su normalia autobiografine atmintimi, flashbackai yra pilni sensorinių detalių, tokių kaip ryškūs vaizdiniai įvaizdžiai, ir gali apimti garsus bei kitas jutimines patirtis. Tačiau šie įvaizdžiai ir pojūčiai paprastai yra suskaldyti ir fragmentiški.",
      "ankstyvos_teorijos": "Ankstyvosios teorijos gali būti suskirstytos į tris tipus. Socialinės-kognityvinės teorijos pirmiausiai dėmesį skiria tam, kaip trauma pažeidžia esamas mentalines struktūras ir įgimtiems mechanizmams, kaip suderinti nesuderinamą informaciją su ankstesniais įsitikinimais. Sąlygojimo teorijos nagrinėja išmoktas asociacijas ir vengimo elgesį. Informacijos apdorojimo teorijos sutelkia dėmesį į baimę keliančių įvykių kodavimą, saugojimą ir atsiminimą bei su jais susijusius stimulus ir reakcijas.",
      "emociju_apdorojimo_teorija": "Foa ir Rothbaum emocinės apdorojimo teorija pabrėžia baimės tinklo svarbą ir tai, kaip traumos atmintis yra organizuota asociatyviame tinkle. Šis požiūris pabrėžia ekspozicijos terapijos svarbą, siekiant susilpninti stiprias asociacijas tarp įvairių traumos elementų atmintyje. Teorija siūlo, kad sėkminga terapija apima baimės aktyvaciją ir habituaciją, taip pat netinkamos informacijos įterpimą į traumos atmintį.",
      "dvigubos_reprezentacijos_teorija": "Brewin, Dalgleish ir Joseph dvigubos reprezentacijos teorija siūlo, kad traumos atmintis yra reprezentuojama dviejose skirtingose atminties sistemose. Verbaliai prieinama atmintis (VAM) apima sąmoningai apdorotą informaciją, kuri gali būti tyčia prisiminta ir integruota į autobiografinę atmintį. Situaciškai prieinama atmintis (SAM) apima žemesnio lygio jutimines detales, kurios nebuvo sąmoningai apdorotos, bet vis tiek buvo užkoduotos. SAM atmintys suaktyvėjamos automatiškai situaciniais priminimais ir pasireiškia kaip flashbackai.",
      "kognityvinis_modelis": "Ehlers ir Clark kognityvinis modelis pabrėžia, kad PTSS išlieka, kai individai apdoroja traumą taip, kad ji sukelia dabartinės grėsmės jausmą. Du pagrindiniai mechanizmai apima neigiamus traumos ar jos pasekmių vertinimus ir traumos atminties pobūdį. Modelis pabrėžia duomenimis grįsto apdorojimo vaidmenį traumos metu, kuris gali lemti, kad atmintis bus prastai elaboruota ir neintegruota į autobiografinę žinių bazę.",
      "bendri_aspektai": "Visos trys naujausios teorijos sutaria, kad vienas iš išgyvenimo nauda yra traumos atminties elaboracija ir kontekstualizacija, tačiau siūlo šiek tiek skirtingus paaiškinimus, kodėl šis procesas yra naudingas. Jos taip pat visos pripažįsta, kad baimė nėra vienintelė svarbi emocija PTSS, ir kad įsitikinimai apie traumą gali apimti daug platesnius aspektus nei tik pavojaus suvokimas.",
      "išvados": "Tarp trijų naujausių PTSS modelių yra didelis sutapimas. Visi jie gali apimti daugybę atradimų apie veiksnius, turinčius įtakos kodavimui, atminties funkcijų pokyčius, vertinimus, įveikos strategijas ir kognityvinius stilius, ankstesnių įsitikinimų ir traumos poveikio svarbą. Svarbiausia sritis, kurioje jie skiriasi, yra jų paaiškinimai, kaip trauma veikia atmintį, procesai, kuriais atmintyje sukuriami pokyčiai, ir kaip šie pokyčiai susiję su pasveikimu. Be to, atminties sutrikimas ir vertinimas yra labiau traktuojami kaip atskiri PTSS aspektai dviejose naujesnėse teorijose nei emocinio apdorojimo teorijoje."
    },
    "saltinis": "Clinical Psychology Review 2003, 23: 339-376",
    "doi": "https://doi.org/10.1016/S0272-7358(03)00033-3",
    "pdf_file": "6_PTSS teorijos_Brewin, Holmes.pdf"
  }
];
